export const allCountries = [
  {
    id: 162,
    titleAr: 'اليمن',
    titleEn: 'Yemen\n',
    countryCode: 'YE',
  },
  {
    id: 163,
    titleAr: 'المملكة العربية السعودية',
    titleEn: 'Saudi Arabia',
    countryCode: 'SA',
  },
  {
    id: 166,
    titleAr: 'مصر',
    titleEn: 'Egypt',
    countryCode: 'EG',
  },
  {
    id: 167,
    titleAr: 'تونس',
    titleEn: 'Tunisia',
    countryCode: 'TN',
  },
  {
    id: 168,
    titleAr: 'فرنسا',
    titleEn: 'France',
    countryCode: 'FR',
  },
  {
    id: 169,
    titleAr: 'الفلبين',
    titleEn: 'Philippines',
    countryCode: 'PH',
  },
  {
    id: 170,
    titleAr: 'أندورا',
    titleEn: 'Andorra',
    countryCode: 'AD',
  },
  {
    id: 172,
    titleAr: 'الإمارات العربية المتحدة',
    titleEn: 'United Arab Emirates',
    countryCode: 'AE',
  },
  {
    id: 173,
    titleAr: 'أفغانستان',
    titleEn: 'Afghanistan',
    countryCode: 'AF',
  },
  {
    id: 175,
    titleAr: 'أنجويلا',
    titleEn: 'Angola',
    countryCode: 'AO',
  },
  {
    id: 176,
    titleAr: 'ألبانيا',
    titleEn: 'Albania',
    countryCode: 'AL',
  },
  {
    id: 177,
    titleAr: 'أرمينيا',
    titleEn: 'Armenia',
    countryCode: 'AM',
  },
  {
    id: 179,
    titleAr: 'أنغولا',
    titleEn: 'Angola',
    countryCode: 'AO',
  },
  {
    id: 180,
    titleAr: 'الأرجنتين',
    titleEn: 'Argentina',
    countryCode: 'AR',
  },
  {
    id: 182,
    titleAr: 'النمسا',
    titleEn: 'Austria',
    countryCode: 'AT',
  },
  {
    id: 183,
    titleAr: 'أستراليا',
    titleEn: 'Australia',
    countryCode: 'AU',
  },
  {
    id: 184,
    titleAr: 'أذربيجان',
    titleEn: 'Azerbaijan',
    countryCode: 'AZ',
  },
  {
    id: 185,
    titleAr: 'البوسنة/الهرسك',
    titleEn: 'Bosnia and Herzegovina',
    countryCode: 'BA',
  },
  {
    id: 186,
    titleAr: 'بنغلاديش',
    titleEn: 'Bangladesh',
    countryCode: 'BD',
  },
  {
    id: 187,
    titleAr: 'بلجيكا',
    titleEn: 'Belgium',
    countryCode: 'BE',
  },
  {
    id: 188,
    titleAr: 'بوركينا فاسو',
    titleEn: 'Burkina Faso',
    countryCode: 'BF',
  },
  {
    id: 189,
    titleAr: 'بلغاريا',
    titleEn: 'Bulgaria',
    countryCode: 'BG',
  },
  {
    id: 190,
    titleAr: 'البحرين',
    titleEn: 'Bahrain',
    countryCode: 'BH',
  },
  {
    id: 191,
    titleAr: 'بنين',
    titleEn: 'Benin',
    countryCode: 'BJ',
  },
  {
    id: 192,
    titleAr: 'بوليفيا',
    titleEn: 'Bolivia',
    countryCode: 'BO',
  },
  {
    id: 193,
    titleAr: 'البرازيل',
    titleEn: 'Brazil',
    countryCode: 'BR',
  },
  {
    id: 194,
    titleAr: 'الباهاماس',
    titleEn: 'Bahamas',
    countryCode: 'BS',
  },
  {
    id: 195,
    titleAr: 'بوتسوانا',
    titleEn: 'Botswana',
    countryCode: 'BW',
  },
  {
    id: 196,
    titleAr: 'روسيا البيضاء',
    titleEn: 'Belarus',
    countryCode: 'BY',
  },
  {
    id: 197,
    titleAr: 'كندا',
    titleEn: 'Canada',
    countryCode: 'CA',
  },
  {
    id: 198,
    titleAr: 'سويسرا',
    titleEn: 'Switzerland',
    countryCode: 'CH',
  },
  {
    id: 199,
    titleAr: 'ساحل العاج',
    titleEn: 'Ivory Coast',
    countryCode: 'CI',
  },
  {
    id: 200,
    titleAr: 'شيلي',
    titleEn: 'Republic of Chile',
    countryCode: 'CL',
  },
  {
    id: 201,
    titleAr: 'كاميرون',
    titleEn: 'Republic of Cameroon',
    countryCode: 'CM',
  },
  {
    id: 202,
    titleAr: 'الصين',
    titleEn: 'China',
    countryCode: 'CN',
  },
  {
    id: 203,
    titleAr: 'كولومبيا',
    titleEn: 'Colombia',
    countryCode: 'CO',
  },
  {
    id: 204,
    titleAr: 'كوستاريكا',
    titleEn: 'Costa Rica',
    countryCode: 'CR',
  },
  {
    id: 205,
    titleAr: 'كوبا',
    titleEn: 'Cuba',
    countryCode: 'CU',
  },
  {
    id: 206,
    titleAr: 'الرأس الأخضر',
    titleEn: 'Cape Verde',
    countryCode: 'CV',
  },
  {
    id: 207,
    titleAr: 'قبرص',
    titleEn: 'Cyprus',
    countryCode: 'CY',
  },
  {
    id: 208,
    titleAr: 'الجمهورية التشيكية',
    titleEn: 'Czech Republic',
    countryCode: 'CZ',
  },
  {
    id: 209,
    titleAr: 'ألمانيا',
    titleEn: 'Germany',
    countryCode: 'DE',
  },
  {
    id: 210,
    titleAr: 'جيبوتي',
    titleEn: 'Djibouti',
    countryCode: 'DJ',
  },
  {
    id: 211,
    titleAr: 'الدانمارك',
    titleEn: 'Denmark',
    countryCode: 'DK',
  },
  {
    id: 212,
    titleAr: 'الجزائر',
    titleEn: 'Algeria',
    countryCode: 'DZ',
  },
  {
    id: 213,
    titleAr: 'إكوادور',
    titleEn: 'Ecuador',
    countryCode: 'EC',
  },
  {
    id: 214,
    titleAr: 'استونيا',
    titleEn: 'Estonia',
    countryCode: 'EE',
  },
  {
    id: 215,
    titleAr: 'إريتريا',
    titleEn: 'Eritrea',
    countryCode: 'ER',
  },
  {
    id: 216,
    titleAr: 'إسبانيا',
    titleEn: 'Spain',
    countryCode: 'ES',
  },
  {
    id: 217,
    titleAr: 'أثيوبيا',
    titleEn: 'Ethiopia',
    countryCode: 'ET',
  },
  {
    id: 218,
    titleAr: 'فنلندا',
    titleEn: 'Finland',
    countryCode: 'FI',
  },
  {
    id: 219,
    titleAr: 'المالديف',
    titleEn: 'Maldives',
    countryCode: 'MV',
  },
  {
    id: 220,
    titleAr: 'الغابون',
    titleEn: 'Gabon',
    countryCode: 'GA',
  },
  {
    id: 221,
    titleAr: 'المملكة المتحدة',
    titleEn: 'United kingdom',
    countryCode: 'GB',
  },
  {
    id: 222,
    titleAr: 'جيورجيا',
    titleEn: 'Georgia',
    countryCode: 'GE',
  },
  {
    id: 223,
    titleAr: 'غانا',
    titleEn: 'Ghana',
    countryCode: 'GH',
  },
  {
    id: 224,
    titleAr: 'غامبيا',
    titleEn: 'Gambia',
    countryCode: 'GM',
  },
  {
    id: 225,
    titleAr: 'غينيا',
    titleEn: 'Guinea',
    countryCode: 'GN',
  },
  {
    id: 226,
    titleAr: 'غينيا الاستوائي',
    titleEn: 'Equatorial Guinea',
    countryCode: 'GQ',
  },
  {
    id: 227,
    titleAr: 'اليونان',
    titleEn: 'Greece',
    countryCode: 'GR',
  },
  {
    id: 228,
    titleAr: 'غواتيمال',
    titleEn: 'Guatemala',
    countryCode: 'GT',
  },
  {
    id: 229,
    titleAr: 'هونغ كونغ',
    titleEn: 'Hong Kong',
    countryCode: 'HK',
  },
  {
    id: 230,
    titleAr: 'هندوراس',
    titleEn: 'Honduras',
    countryCode: 'HN',
  },
  {
    id: 231,
    titleAr: 'كرواتيا',
    titleEn: 'Croatia',
    countryCode: 'HR',
  },
  {
    id: 232,
    titleAr: 'هايتي',
    titleEn: 'Haiti',
    countryCode: 'HT',
  },
  {
    id: 233,
    titleAr: 'هنغاريا',
    titleEn: 'Hungary',
    countryCode: 'HU',
  },
  {
    id: 234,
    titleAr: 'أندونيسيا',
    titleEn: 'Indonesia',
    countryCode: 'ID',
  },
  {
    id: 235,
    titleAr: 'أيرلندا',
    titleEn: 'Ireland',
    countryCode: 'IE',
  },
  {
    id: 236,
    titleAr: 'الهند',
    titleEn: 'India',
    countryCode: 'IN',
  },
  {
    id: 237,
    titleAr: 'العراق',
    titleEn: 'Iraq',
    countryCode: 'IQ',
  },
  {
    id: 238,
    titleAr: 'إيران',
    titleEn: 'Iran',
    countryCode: 'IR',
  },
  {
    id: 239,
    titleAr: 'آيسلندا',
    titleEn: 'Iceland',
    countryCode: 'IS',
  },
  {
    id: 240,
    titleAr: 'إيطاليا',
    titleEn: 'Italy',
    countryCode: 'IT',
  },
  {
    id: 241,
    titleAr: 'جمايكا',
    titleEn: 'Jamaica',
    countryCode: 'JM',
  },
  {
    id: 242,
    titleAr: 'الأردن',
    titleEn: 'Jordan',
    countryCode: 'JO',
  },
  {
    id: 243,
    titleAr: 'اليابان',
    titleEn: 'Japan',
    countryCode: 'JP',
  },
  {
    id: 244,
    titleAr: 'كينيا',
    titleEn: 'Kenya',
    countryCode: 'KE',
  },
  {
    id: 245,
    titleAr: 'قيرغيزستان',
    titleEn: 'Kyrgyzstan',
    countryCode: 'KG',
  },
  {
    id: 246,
    titleAr: 'كوريا الشمالية',
    titleEn: 'Korea North',
    countryCode: 'KP',
  },
  {
    id: 247,
    titleAr: 'كوريا الجنوبية',
    titleEn: 'Korea South',
    countryCode: 'KR',
  },
  {
    id: 248,
    titleAr: 'الكويت',
    titleEn: 'Kuwait',
    countryCode: 'KW',
  },
  {
    id: 249,
    titleAr: 'كازاخستان',
    titleEn: 'Kazakhstan',
    countryCode: 'KZ',
  },
  {
    id: 250,
    titleAr: 'لبنان',
    titleEn: 'Lebanon',
    countryCode: 'LB',
  },
  {
    id: 251,
    titleAr: 'سريلانكا',
    titleEn: 'Sri Lanka',
    countryCode: 'LK',
  },
  {
    id: 252,
    titleAr: 'ليبيريا',
    titleEn: 'Liberia',
    countryCode: 'LR',
  },
  {
    id: 253,
    titleAr: 'لتوانيا',
    titleEn: 'Lithuania',
    countryCode: 'LT',
  },
  {
    id: 254,
    titleAr: 'لوكسمبورغ',
    titleEn: 'Luxembourg',
    countryCode: 'LU',
  },
  {
    id: 255,
    titleAr: 'ليبيا',
    titleEn: 'Libya',
    countryCode: 'LY',
  },
  {
    id: 256,
    titleAr: 'المغرب',
    titleEn: 'Morocco\n',
    countryCode: 'MA',
  },
  {
    id: 257,
    titleAr: 'الجبل الأسود',
    titleEn: 'Montenegro',
    countryCode: 'ME',
  },
  {
    id: 258,
    titleAr: 'مدغشقر',
    titleEn: 'Madagascar',
    countryCode: 'MG',
  },
  {
    id: 259,
    titleAr: 'مقدونيا',
    titleEn: 'Macedonia',
    countryCode: 'MK',
  },
  {
    id: 260,
    titleAr: 'مالي',
    titleEn: 'Mali',
    countryCode: 'ML',
  },
  {
    id: 261,
    titleAr: 'منغوليا',
    titleEn: 'Mongolia',
    countryCode: 'MN',
  },
  {
    id: 262,
    titleAr: 'موريتانيا',
    titleEn: 'Mauritania',
    countryCode: 'MR',
  },
  {
    id: 263,
    titleAr: 'مالطا',
    titleEn: 'Malta',
    countryCode: 'MT',
  },
  {
    id: 264,
    titleAr: 'مالاوي',
    titleEn: 'Malawi ',
    countryCode: 'MW',
  },
  {
    id: 265,
    titleAr: 'المكسيك',
    titleEn: 'Mexico',
    countryCode: 'MX',
  },
  {
    id: 266,
    titleAr: 'ماليزيا',
    titleEn: 'Malaysia',
    countryCode: 'MY',
  },
  {
    id: 267,
    titleAr: 'موزمبيق',
    titleEn: 'Mozambique',
    countryCode: 'MZ',
  },
  {
    id: 268,
    titleAr: 'ناميبيا',
    titleEn: 'Namibia ',
    countryCode: 'NA',
  },
  {
    id: 269,
    titleAr: 'النيجر',
    titleEn: 'Niger ',
    countryCode: 'NE',
  },
  {
    id: 270,
    titleAr: 'نيجيريا',
    titleEn: 'Nigeria',
    countryCode: 'NG',
  },
  {
    id: 271,
    titleAr: 'نيكاراجوا',
    titleEn: 'Nicaragua',
    countryCode: 'NI',
  },
  {
    id: 272,
    titleAr: 'هولندا',
    titleEn: 'Netherlands',
    countryCode: 'NL',
  },
  {
    id: 273,
    titleAr: 'النرويج',
    titleEn: 'Norway',
    countryCode: 'NO',
  },
  {
    id: 274,
    titleAr: 'نيبال',
    titleEn: 'Nepal\n',
    countryCode: 'NP',
  },
  {
    id: 275,
    titleAr: 'نيوزيلندا',
    titleEn: 'New Zealand',
    countryCode: 'NZ',
  },
  {
    id: 276,
    titleAr: 'عُمان',
    titleEn: 'Oman',
    countryCode: 'OM',
  },
  {
    id: 277,
    titleAr: 'بنما',
    titleEn: 'Panama',
    countryCode: 'PA',
  },
  {
    id: 278,
    titleAr: 'بيرو',
    titleEn: 'Peru',
    countryCode: 'PE',
  },
  {
    id: 279,
    titleAr: 'باكستان',
    titleEn: 'Pakistan',
    countryCode: 'PK',
  },
  {
    id: 280,
    titleAr: 'بولندا',
    titleEn: 'Poland',
    countryCode: 'PL',
  },
  {
    id: 281,
    titleAr: 'فلسطين',
    titleEn: 'Palestine \n',
    countryCode: 'PS',
  },
  {
    id: 282,
    titleAr: 'البرتغال',
    titleEn: 'Portugal',
    countryCode: 'PT',
  },
  {
    id: 283,
    titleAr: 'بالاو',
    titleEn: 'Palau',
    countryCode: 'PW',
  },
  {
    id: 284,
    titleAr: 'باراغواي',
    titleEn: 'Paraguay',
    countryCode: 'PY',
  },
  {
    id: 285,
    titleAr: 'قطر',
    titleEn: 'Qatar\n',
    countryCode: 'QA',
  },
  {
    id: 286,
    titleAr: 'رومانيا',
    titleEn: 'Romania',
    countryCode: 'RO',
  },
  {
    id: 287,
    titleAr: 'صربيا',
    titleEn: 'Serbia\n',
    countryCode: 'RS',
  },
  {
    id: 288,
    titleAr: 'روسيا',
    titleEn: 'Russia',
    countryCode: 'RU',
  },
  {
    id: 289,
    titleAr: 'رواندا',
    titleEn: 'Rwanda',
    countryCode: 'RW',
  },
  {
    id: 290,
    titleAr: 'سيشيل',
    titleEn: 'Seychelles',
    countryCode: 'SC',
  },
  {
    id: 291,
    titleAr: 'السودان',
    titleEn: 'Sudan',
    countryCode: 'SD',
  },
  {
    id: 292,
    titleAr: 'السويد',
    titleEn: 'Sweden',
    countryCode: 'SE',
  },
  {
    id: 293,
    titleAr: 'سنغافورة',
    titleEn: 'Singapore',
    countryCode: 'SG',
  },
  {
    id: 294,
    titleAr: 'سلوفينيا',
    titleEn: 'Slovenia',
    countryCode: 'SI',
  },
  {
    id: 295,
    titleAr: 'سلوفاكيا',
    titleEn: 'Slovakia',
    countryCode: 'SK',
  },
  {
    id: 296,
    titleAr: 'سيراليون',
    titleEn: 'Sierra Leone',
    countryCode: 'SL',
  },
  {
    id: 297,
    titleAr: 'السنغال',
    titleEn: 'Senegal',
    countryCode: 'SN',
  },
  {
    id: 298,
    titleAr: 'الصومال',
    titleEn: 'Somalia',
    countryCode: 'SO',
  },
  {
    id: 299,
    titleAr: 'سورية',
    titleEn: 'Syria\n',
    countryCode: 'SY',
  },
  {
    id: 300,
    titleAr: 'تشاد',
    titleEn: 'Chad',
    countryCode: 'TD',
  },
  {
    id: 301,
    titleAr: 'توغو',
    titleEn: 'Togo',
    countryCode: 'TG',
  },
  {
    id: 302,
    titleAr: 'تايلندا',
    titleEn: 'Thailand\n',
    countryCode: 'TH',
  },
  {
    id: 303,
    titleAr: 'طاجيكستان',
    titleEn: 'Tajikistan',
    countryCode: 'TJ',
  },
  {
    id: 304,
    titleAr: 'تركيا',
    titleEn: 'Turkey',
    countryCode: 'TR',
  },
  {
    id: 305,
    titleAr: 'ترينيداد وتوباغو',
    titleEn: 'Republic of Trinidad and Tobago',
    countryCode: 'TT',
  },
  {
    id: 306,
    titleAr: 'تايوان',
    titleEn: 'Taiwan',
    countryCode: 'TW',
  },
  {
    id: 307,
    titleAr: 'تنزانيا',
    titleEn: 'Tanzania',
    countryCode: 'TZ',
  },
  {
    id: 308,
    titleAr: 'أوكرانيا',
    titleEn: 'Ukraine',
    countryCode: 'UA',
  },
  {
    id: 309,
    titleAr: 'أوغندا',
    titleEn: 'Republic of Uganda',
    countryCode: 'UG',
  },
  {
    id: 310,
    titleAr: 'الولايات المتحدة',
    titleEn: 'United States of America',
    countryCode: 'US',
  },
  {
    id: 311,
    titleAr: 'أورغواي',
    titleEn: 'Uruguay \n',
    countryCode: 'UY',
  },
  {
    id: 312,
    titleAr: 'أوزباكستان',
    titleEn: 'Uzbekistan',
    countryCode: 'UZ',
  },
  {
    id: 313,
    titleAr: 'فنزويلا',
    titleEn: 'Venezuela',
    countryCode: 'VE',
  },
  {
    id: 314,
    titleAr: 'فيتنام',
    titleEn: 'Vietnam',
    countryCode: 'VN',
  },
  {
    id: 316,
    titleAr: 'جنوب أفريقيا',
    titleEn: 'South Africa',
    countryCode: 'ZA',
  },
  {
    id: 317,
    titleAr: 'زامبيا',
    titleEn: 'Zambia',
    countryCode: 'ZM',
  },
  {
    id: 318,
    titleAr: 'زمبابوي',
    titleEn: 'Zimbabwe',
    countryCode: 'ZW',
  },
  {
    id: 319,
    titleAr: 'الكونغو',
    titleEn: 'Congo ',
    countryCode: 'CG',
  },
  {
    id: 320,
    titleAr: 'فيجي',
    titleEn: 'Fiji',
    countryCode: 'FJ',
  },
  {
    id: 321,
    titleAr: 'سوازيلاند',
    titleEn: 'Swaziland',
    countryCode: 'SZ',
  },
  {
    id: 322,
    titleAr: 'السلفادور',
    titleEn: 'El Salvador',
    countryCode: 'SV',
  },
  {
    id: 323,
    titleAr: 'بابوا غينيا الجديدة',
    titleEn: 'Papua New Guinea',
    countryCode: 'PG',
  },
  {
    id: 324,
    titleAr: 'باربادوس',
    titleEn: 'Barbados',
    countryCode: 'BB',
  },
  {
    id: 325,
    titleAr: 'بروناي',
    titleEn: 'Brunei',
    countryCode: 'BN',
  },
  {
    id: 326,
    titleAr: 'بليز',
    titleEn: 'Belize',
    countryCode: 'BZ',
  },
  {
    id: 327,
    titleAr: 'بورتوريكو',
    titleEn: 'Puerto Rico',
    countryCode: 'PR',
  },
  {
    id: 328,
    titleAr: 'تونغا',
    titleEn: 'Tonga',
    countryCode: 'TO',
  },
  {
    id: 329,
    titleAr: 'جزر الآنتيل الهولندية',
    titleEn: 'Netherlands Antilles',
    countryCode: 'NL',
  },
  {
    id: 330,
    titleAr: 'جزر البهاما',
    titleEn: 'Bahamas Islands',
    countryCode: 'BS',
  },
  {
    id: 331,
    titleAr: 'جزر سليمان',
    titleEn: 'Solomon Islands',
    countryCode: 'SB',
  },
  {
    id: 332,
    titleAr: 'جزر سيشل',
    titleEn: 'Seychelles Islands',
    countryCode: 'SC',
  },
  {
    id: 333,
    titleAr: 'جزر كايمان',
    titleEn: 'Cayman Islands',
    countryCode: 'KY',
  },
  {
    id: 334,
    titleAr: 'جزر مارشال',
    titleEn: 'Republic of the Marshall Islands',
    countryCode: 'MH',
  },
  {
    id: 335,
    titleAr: 'جزر ريونيون',
    titleEn: 'Réunion Islands',
    countryCode: 'RE',
  },
  {
    id: 336,
    titleAr: 'جمهورية الدومينيكان',
    titleEn: 'Dominican Republic',
    countryCode: 'DO',
  },
  {
    id: 337,
    titleAr: 'جنوب السودان',
    titleEn: 'South Sudan',
    countryCode: 'SS',
  },
  {
    id: 339,
    titleAr: 'الدومينيكان',
    titleEn: 'Dominican Republic',
    countryCode: 'DO',
  },
  {
    id: 340,
    titleAr: 'ساموا الأمريكية',
    titleEn: 'American Samoa',
    countryCode: 'WS',
  },
  {
    id: 341,
    titleAr: 'سريلانكا',
    titleEn: 'Sri Lanka\n',
    countryCode: 'LK',
  },
  {
    id: 342,
    titleAr: 'سانت فنسنت والجرينادين',
    titleEn: 'St Vincent and Grenadine',
    countryCode: 'VC',
  },
  {
    id: 344,
    titleAr: 'سانت كيتس ونيفيس',
    titleEn: 'St Kitts and Nevis',
    countryCode: 'KN',
  },
  {
    id: 345,
    titleAr: 'سانت لوسيا',
    titleEn: 'St Lucia',
    countryCode: 'LC',
  },
  {
    id: 346,
    titleAr: 'ماكاو',
    titleEn: 'Macau',
    countryCode: 'MO',
  },
  {
    id: 347,
    titleAr: 'موريشيوس',
    titleEn: 'Mauritius\n',
    countryCode: 'MU',
  },
  {
    id: 348,
    titleAr: 'مولدوفا',
    titleEn: 'Moldova',
    countryCode: 'MD',
  },
  {
    id: 349,
    titleAr: 'ميانمار، بورما',
    titleEn: 'Myanmar, Burma',
    countryCode: 'MM',
  },
  {
    id: 352,
    titleAr: 'كوسوفا',
    titleEn: 'Kosovo',
    countryCode: 'XZ',
  },
  {
    id: 353,
    titleAr: 'دولة البط',
    titleEn: 'Duck Country',
    countryCode: 'KH',
  },
  {
    id: 354,
    titleAr: 'سوريا',
    titleEn: 'Syria',
    countryCode: 'Sy',
  },
  {
    id: 355,
    titleAr: 'اختبار دولة',
    titleEn: 'Saudi Arabia',
    countryCode: 'SA',
  },
];

export const getCountryCodeById = (countryId: number) => {
  let country = allCountries.filter((c) => countryId === c?.id);
  return country[0]?.countryCode;
};
export const getCountryIdByCode = (countryCode: string) => {
  let country = allCountries.filter((c) => countryCode === c?.countryCode);
  return country[0]?.id;
};
export const getCountryNameByCode = (countryCode: string) => {
  let country = allCountries.filter((c) => countryCode === c?.countryCode);
  return country[0]?.id;
};
export const getCountryNameById = (countryId: number) => {
  let country = allCountries.filter((c) => countryId === c?.id);
  return country[0]?.titleEn;
};
